package com.greedao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lcm.app.data.entity.WelfareBean;

import com.greedao.dao.WelfareBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig welfareBeanDaoConfig;

    private final WelfareBeanDao welfareBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        welfareBeanDaoConfig = daoConfigMap.get(WelfareBeanDao.class).clone();
        welfareBeanDaoConfig.initIdentityScope(type);

        welfareBeanDao = new WelfareBeanDao(welfareBeanDaoConfig, this);

        registerDao(WelfareBean.class, welfareBeanDao);
    }
    
    public void clear() {
        welfareBeanDaoConfig.clearIdentityScope();
    }

    public WelfareBeanDao getWelfareBeanDao() {
        return welfareBeanDao;
    }

}
